spring: 
   application: 
      name: index-codes-service 
#服务链路追踪
   zipkin: 
      base-url: http://localhost:9411
eureka: 
   client: 
      serviceUrl: 
         defaultZone: http://localhost:8761/eureka/